### PR TITLE
packr -> pkger, split docker files

### PR DESCRIPTION
**Pull request by adam-stanek**
I have created dedicated docker files for each of the applications (document and thumbnail processor) so that it is easy to build each application. With this approach it is much easier to manage running instances.

- The document processor already provides rich means of configuration, yet it was not easy to provide it. In my set up I wanted to tweak elasticsearch mapping for better text analysis. Application already have means how to do it, but you cannot provide necessary CLI arguments because it is all wrapped in S6.
- Docker images can be much more lean. I have managed to build document processor based on scratch image so it is very tiny. The thumbnail processor is also leaner, but we could go even further if we build the imagick from source without x11 dependencies.
- Joint logs of multiple services are hard for operations. It is much easier to manage them separately.
- Generally it is considered best practice to keep single process per container. Including own init systems makes your live unnecessarily difficult, especially when you want to run application in production ready kubernetes cluster.

While doing this I run into some problems with packr. I have discovered that the project is already in maintenance mode and it was surpassed by pkger. I have updated the project to the newer, maintained library (doing the same thing).

### CODE REVIEW

**Comment by adam-stanek** [comment]
Please note, that this will require change of the `docker-compose` in the main repo. It should now include two containers for each image with appropriate CLI arguments.

Here is an example (instead of existing processor definition):

```yaml
  document_processor:
    image: lodestone-document-processor:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      webapp:
        condition: service_healthy
      tika:
        condition: service_healthy
    command:
    - /lodestone-document-processor
    - start
    - --amqp-url=amqp://lodestone:lodestone@rabbitmq:5672
    - --api-endpoint=http://webapp:3000
    - --tika-endpoint=http://tika:9998
    - --elasticsearch-endpoint=http://elasticsearch:9200
    
  thumbnail_processor:
    image: lodestone-thumbnail-processor:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
      webapp:
        condition: service_healthy
    command:
    - /usr/bin/lodestone-thumbnail-processor
    - start
    - --amqp-url=amqp://lodestone:lodestone@rabbitmq:5672
    - --api-endpoint=http://webapp:3000
```

**Comment by dskaggs** [comment]
Thanks so much for taking the time to create a PR. I have some questions, and since I'm not a Go dev, please be patient:

1. If I'm reading the PR right, we've now split the `lodestone-processor` repo into 2 separate Docker images? Does that mean each time we want to add a new way of processing documents (such as adding the email processor eventually), we add an additional Docker image for each one?
2. If the above is true, how does this affect the auto build system that I just set up yesterday at DockerHub? (https://hub.docker.com/repository/docker/lodestonehq/lodestone-processor)
3. In talking with a friend of mine, it appears the Go community is moving away from DEPS and to modules. Does this effort do anything to make that migration easier or is that a separate issue?

**Comment by adam-stanek** [comment]
> If I'm reading the PR right, we've now split the lodestone-processor repo into 2 separate Docker images? Does that mean each time we want to add a new way of processing documents (such as adding the email processor eventually), we add an additional Docker image for each one?

Yes it produces 2 docker images. And yes, e-mail processor should most likely be separate docker image too. The lodestone project seems to be build like a set of standalone applications (document processor, thumbnail processor, filesystem publisher, e-mail publisher, ...). They have been however packaged together in single image and built all together in the main lodestone repo. This can cause a lot of problems, as described above and in few of the issues I created in the main project.

> If the above is true, how does this affect the auto build system that I just set up yesterday at DockerHub? (https://hub.docker.com/repository/docker/lodestonehq/lodestone-processor)

Sorry, I don't know much about what you did with DockerHub auto build, it is not publicly accessible, only the images are. But yes, you will need to adjust it to build both images.

> In talking with a friend of mine, it appears the Go community is moving away from DEPS and to modules. Does this effort do anything to make that migration easier or is that a separate issue?

This project is already using Go modules. DEPS are used in the publisher project though and yes, it would be best to get it replaced with now standard Go modules.

**Comment by dskaggs** [comment]
Ok, I think I have figured out a way to do that. I can create 2 different repos in DockerHub that point to the same GitHub repo and specify a the appropriate Dockerfile for each one. That will create the separate images that will then be used in the updated compose file that you mention above.

Let me get that set up before I merge your PR and so we can make sure the automation works. Then we can go about updatine the docker-compose file with the changes you suggested above. We'll also need to look at how this affects the DEV docker-compose file as it runs a build using assets in the main `lodestone` repo.

**Review by dskaggs — APPROVED** [review]

**Comment by adam-stanek** [comment]
That might be a way, true.

I just quickly checked the dev docker-compose and to be honest I don't think it is worth keeping it at all. It does the same thing but with bind mounted binaries from your local machine. The thing is that every developer is going to have this different. He might not even be developing all the packages. Also some of the packages have dependencies (ie. imagick) and I don't expect people are going to install those in project versions on their own machines. Stuff like that is usually developed inside their own containers which serve as platform independent development environment. I think that the idea of the dev docker-compose served well to the original author because it was tailored to his own environment, but won't be too helpful to anybody else.

Instead you should build the image with now provided means and just use it in your main docker-compose.

**Comment by dskaggs** [comment]
That's kinda what I thought as well. Seems to me if you are working on one of the other packages, you rebuild the Docker image locally and restart the stack to check the integration with the other parts. I'll create a ticket to sort that out.

I just merged the PR and both the new DockerHub repos are building `latest`. Once I know that works, I'll create a release/tag and get the version tag built there too.

Thank you again for the PR!

**Comment by dskaggs** [comment]
Fixes: https://github.com/LodestoneHQ/lodestone/issues/111

**Pull request merged**
